name: Redirects
version: 1.2.0
description: 'Manages URL redirects and monitors 404 requests.'
url: 'https://statamic.com/marketplace/addons/redirects'
developer: Gridonic
developer_url: 'https://gridonic.ch'
commercial: true
